name: SonarCloud analysis

on:
  push:
    branches:
      - sonarcloud
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: read 

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'

      - name: Install ReportGenerator tool
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Build project
        run: dotnet build

      - name: Run tests with coverage
        run: dotnet test --collect:"XPlat Code Coverage"

      - name: Generate coverage report in JaCoCo format
        run: |
          reportgenerator -reports:"**/coverage.cobertura.xml" -targetdir:"coverage-report"
          mv coverage-report/coverage.xml coverage.xml 

      - name: Log coverage report content
        run: |
          cat coverage.xml

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
        with:
          args:
            -Dsonar.projectKey=DrengeneFraKEA_Hovedopgave
            -Dsonar.organization=drengenefrakea
            -Dsonar.coverage.jacoco.xmlReportPaths=coverage.xml 
          projectBaseDir: .
