name: SonarCloud analysis

on:
  push:
    branches:
      - sonarcloud
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: read 

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'

      - name: Install dotnet-sonarscanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet-sonarscanner --version
          
      - name: Install dotnet-coverage
        run: |
          dotnet tool install --global dotnet-coverage
          dotnet tool list --global
          dotnet-coverage --version

      - name: Begin SonarCloud analysis
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"DrengeneFraKEA_Hovedopgave" /o:"drengenefrakea" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
  
      - name: Build project
        run: dotnet build

      - name: End SonarCloud analysis
        run: |
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
