name: Tests

on:
  push:
    branches:
      - master
      - '#50-update-workflows-secrets' 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Environment variables
        run: |
          echo "AZURE_DB_USERNAME="${{ secrets.AZURE_DB_USERNAME }}"" >> $GITHUB_ENV
          echo "AUZRE_DB_PASSWORD="${{ secrets.AZURE_DB_PASSWORD }}"" >> $GITHUB_ENV
          echo "AZURE_DB_HOST="${{ secrets.AZURE_DB_HOST }}"" >> $GITHUB_ENV
          echo "AZURE_DB_DATABASE="${{ secrets.AZURE_DB_DATABASE }}"" >> $GITHUB_ENV
          echo "PASSWORD_HASH="${{ secrets.PASSWORD_HASH }}"" >> $GITHUB_ENV
          echo "JWT_TOKEN="${{ secrets.JWT_TOKEN }}"" >> $GITHUB_ENV
      
      - name: Test
        run: dotnet test
