name: Tests

on:
  push:
    branches:
      - dev
      - master
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Environment variables
        run: |
          echo "AZURE_DB_USERNAME="${{ secrets.AZURE_DB_USERNAME }}"" >> ./Hovedopgave.Server/env.env
          echo "AZURE_DB_PASSWORD="${{ secrets.AZURE_DB_PASSWORD }}"" >> ./Hovedopgave.Server/env.env
          echo "AZURE_DB_HOST="${{ secrets.AZURE_DB_HOST }}"" >> ./Hovedopgave.Server/env.env
          echo "AZURE_DB_DATABASE="${{ secrets.AZURE_DB_DATABASE }}"" >> ./Hovedopgave.Server/env.env
          echo "PASSWORD_HASH="${{ secrets.PASSWORD_HASH }}"" >> ./Hovedopgave.Server/env.env
          echo "JWT_TOKEN="${{ secrets.JWT_TOKEN }}"" >> ./Hovedopgave.Server/env.env

      - name: Test
        run: dotnet test
        continue-on-error: true
